apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hkuaaj528-go 
  janus-idp.io/tekton: hkuaaj528-go
  backstage.io/kubernetes-id: hkuaaj528-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkuaaj528-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml