apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hkuaaj528-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hkuaaj528-go 
  name: hkuaaj528-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hkuaaj528-go 
